version: '3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: groozzy/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/var/www/kittygram/media
    depends_on:
      - db
    restart: on-failure

  frontend:
    env_file: .env
    image: groozzy/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
      - media:/var/www/kittygram/media
    restart: no

  gateway:
    image: groozzy/kittygram_gateway
    env_file: .env
    ports:
      - {NGINX_PORT}:80
    volumes:
      - static:/staticfiles/
      - media:/var/www/kittygram/media
    restart: always
